name:                ConfigHs
version:             0.1.0.0
github:              "TimeTravelPenguin/ConfigHs"
license:             BSD-3-Clause
author:              "Phillip Smith"
maintainer:          "TimeTravelPenguin@gmail.com"
copyright:           "2023 Phillip Smith"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TimeTravelPenguin/ConfigHs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.1.2.1
- text >= 2.0.2
- mtl >= 2.2.2
- containers >= 0.6.7
- path >= 0.9.5
- path-io >= 1.8.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ConfigHs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ConfigHs

tests:
  ConfigHs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ConfigHs
